"""empty message

Revision ID: 8465bcac1abd
Revises: a238e62d106a
Create Date: 2026-06-12 04:16:35.987386

"""

# revision identifiers, used by Alembic.
revision = '8465bcac1abd'
down_revision = 'a238e62d106a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
